version: "3.9"

services:
  web:
    build: frontend
    container_name: social-network-frontend
    restart: always
    ports: 
      - 80:3000
    depends_on:
      - api

  api:
    build: api
    container_name: social-network-api
    restart: always
    environment:
      - "PORT=${PORT}"
      - "FRONTEND_URL=${FRONTEND_URL}"
      - "MONGO_URL=${MONGO_URL}"
      - "SECRET=${SECRET}"
      - "CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}"
      - "CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}"
      - "CLOUDINARY_SECRET=${CLOUDINARY_SECRET}"
    ports:
      - 4000:4000
    depends_on:
      - api-db
    networks:
      - social-network  

  api-db:
    image: mongo:5.0.3
    container_name: social-network-db
    restart: always
    volumes:
      - /data/social-network:/data/db
    networks:
      - social-network

networks:
  social-network: