version: "3.9"

services:
  web:
    image: benjamimunifor/create-social-network-web:latest
    ports:
      - 80:3000
    depends_on:
      - api

  api:
    image: benjamimunifor/create-social-network-api:latest
    environment:
      - PORT=${PORT}
      - FRONTEND_URL=${FRONTEND_URL}
      - MONGO_URL=${MONGO_URL}
      - SECRET=${SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
    ports:
      - 4000:4000
    depends_on:
      - api-db
    networks:
      - social-network

  api-db:
    image: mongo:5.0.3
    volumes:
      - /data/social-network:/data/db
    networks:
      - social-network
    deploy:
      placement:
        constraints: [node.hostname == arch]

networks:
  social-network:
