name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [ 16.10 ]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}

      - name: Test API
        run: |
          cd api
          npm i && \
          npm run test --if-present && \
          sed -i '/"type": "module"/d' package.json && \
          cd ..

      - name: Test Frontend
        run: |
          cd frontend
          npm i && \
          npm run test --if-present
          cd ..
      
      - name: Build docker images
        run: |
          docker build frontend --rm -t benjamimunifor/create-social-network-web:latest &&
          docker build api --rm -t benjamimunifor/create-social-network-api:latest
        
      - name: Push images to docker hub
        run: |
          docker push benjamimunifor/create-social-network-web:latest &&
          docker push benjamimunifor/create-social-network-api:latest
      
      - name: Deploy application to docker swarm
        run: |
          docker stack deploy -c docker-compose.yaml create-social-network
