name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [ 16.10 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}

      # Runs a single command using the runners shell
      - name: Test API
        run: |
          cd api
          npm i && \
          npm run test --if-present && \
          sed -i '/"type": "module"/d' package.json && \
          cd ..

      # Runs a set of commands using the runners shell
      - name: Test Frontend
        run: |
          cd frontend
          npm i && \
          npm run test --if-present
          cd ..
      
      - name: Build docker images
        run: |
          docker build frontend --rm -t benjamimunifor/create-social-network-web:latest &&
          docker build api --rm -t benjamimunifor/create-social-network-api:latest
        
      - name: Push images to docker hub
        run: |
          docker push benjamimunifor/create-social-network-web:latest &&
          docker push benjamimunifor/create-social-network-api:latest
      
      - name: Deploy application to docker swarm
        run: |
          docker stack deploy -c docker-compose.yaml create-social-network
